name: spenix_internet
description: Spenix Internet – VPN & Internet Provider
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  http: ^1.2.2
  wireguard_flutter: ^0.0.6   # ✅ Correct package
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
